### ISSUE TITLE
Carthage Installation Error

### ISSUE THREAD

**Issue by abrarEpazz** [coinbase/coinbase-ios-sdk#48] opened 2019-04-09 15:04 UTC
Hi!, Please help me how to fix this. when I trying to install coinbase-ios-SDK in my project this error occur.

*** Skipped building coinbase-ios-SDK due to the error:
Dependency "coinbase-ios-SDK" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/coinbase/coinbase-ios-sdk/issues/new

**Comment by StanislavKrishu** [comment] 2019-04-09 15:13
Hey, 
Looks like you use `Carthage` and it relies on `GitHub` release which seems to be outdated. Try to specify branch or commit in your `Cartfile`, e.g.
```
github "coinbase/coinbase-ios-sdk" "master"
```

**Comment by abrarEpazz** [comment] 2019-04-09 15:44
> Hey,
> Looks like you use `Carthage` and it relies on `GitHub` release which seems to be outdated. Try to specify branch or commit in your `Cartfile`, e.g.
> 
> ```
> github "coinbase/coinbase-ios-sdk" "master"
> ```

Hi, Thanks for your reply, I'm trying this as you said, but still 1 thing is Skipped during installation.

*** Downloading RxSwift.framework binary at "[4,5]"
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

**Comment by StanislavKrishu** [comment] 2019-04-09 16:01
Could you try to run update command with `--no-use-binaries`

```
carthage update --platform iOS --no-use-binaries
```

**Comment by abrarEpazz** [comment] 2019-04-09 16:08
Yes, i use "carthage update --platform iOS" and also trying "carthage update --no-use-binaries"

**Comment by StanislavKrishu** [comment] 2019-04-09 16:09
Have you tried removing `Carthage` folder and re run again `carthage update --platform iOS --no-use-binaries`?

**Comment by abrarEpazz** [comment] 2019-04-09 16:12
No, but i already try to uninstall and reinstall carthage from my system.

**Comment by StanislavKrishu** [comment] 2019-04-09 16:14
Also, could you please run `swift -version` 
I assume you don't use the latest Xcode for some reason

**Comment by abrarEpazz** [comment] 2019-04-09 16:17
i use this swift -version: 
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.5.0

**Comment by StanislavKrishu** [comment] 2019-04-09 16:38
> *** Skipped installing RxSwift.framework binary due to the error:
> "Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

Was able to reproduce this message by using an older version of Xcode. Though it builds successfully. It just builds from the source
```
***  Skipped installing RxSwift.framework binary due to the error:
        "Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)."

    Falling back to building from the source
*** Building scheme "RxAtomic" in Rx.xcworkspace
```
Are you positive that there is a problem?

**Comment by abrarEpazz** [comment] 2019-04-10 08:23
> positive that there is a problem?

Yes, I have an issue but I think my swift version is older then framework required version, by the way, thanks for helping me. I can update my Xcode and then try to implement if the issue still there after the update then I will post again. Thanks once again :)

**Comment by abrarEpazz** [comment] 2019-04-12 13:59
Hi!, @StanislavKrishu I have successfully installed "coinbase-ios-SDK" thanks for your help. I need more help related to Currency Exchange, Currency Convert and Money Transfer in IOS app. Please help me how I do these things in my IOS project? Thanks

**Comment by StanislavKrishu** [comment] 2019-04-12 15:24
Hey, @abrarEpazz, glad that you resolved these issues.
Have you tried the sample app? It might be a good starting point to see how to use the SDK. 
Also, there are some [instructions and examples](https://github.com/coinbase/coinbase-ios-sdk/wiki/Examples) that might help
You can take a look at [API docs](https://developers.coinbase.com/api/v2) to see what this SDK does

Let me know if you have issues running the sample app

**Comment by abrarEpazz** [comment] 2019-04-15 10:46
Hi!, @StanislavKrishu Can we use a bank payment method in iOS App like First, we get all bank information through a form in iOS app and then we link this account to Coinbase and after that, we send our money in a bank? 

I'm confused about how to integrate bank account in iOS App, and then send money from one bank account to another.

**Comment by azammuminov** [comment] 2021-04-12 03:45
> Hi!, @StanislavKrishu I have successfully installed "coinbase-ios-SDK" thanks for your help. I need more help related to Currency Exchange, Currency Convert and Money Transfer in IOS app. Please help me how I do these things in my IOS project? Thanks

Hi. How r u doing. May I know your solution? how did u solve that?

**Comment by jwitcig** [comment] 2022-01-01 05:35
Hi all, hope we were able to make it past this issue.
I'll be closing this out now as we are [deprecating the SDK](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75).

I would like to thank you all for your contributions.

**Closed as completed by jwitcig** 2022-01-01 05:35 UTC
